### PR TITLE
Перевод Architecture, Projects, Routing

### PR DESCRIPTION
**Pull request by GeorgeGorbanev**
### Architecture
- [x] Overview
### Projects
- [x] Code Reloading
- [x] Rake
- [x] Logging
- [x] Initializers
### Routing
- [x] Overview
- [x] Basic Usage
- [x] RESTful Resource(s)
- [x] Testing
### Actions
- [x] Overview
- [x] Basic Usage
- [x] Parameters
- [x] Request & Response
- [x] Exposures
- [x] Rack Integration
- [x] MIME Types
- [x] Cookies
- [x] Sessions
- [x] Exception Handling
- [x] Control Flow
- [x] HTTP Caching
- [x] Share Code
- [x] Testing
### Views
- [x] Overview
- [x] Basic Usage
- [x] Templates
- [x] MIME Types
- [x] Layouts
- [x] Custom Error Pages
- [x] Share Code
- [x] Testing
### Models
- [x] Overview
- [x] Repositories
- [x] Entities
- [x] Data Types
- [x] PostgreSQL
- [x] Associations
- [x] Use Your Own ORM
### Migrations
- [x] Overview
- [x] Create Table
- [x] Alter Table
### Helpers
- [x] Overview
- [x] HTML5
- [x] Forms
- [x] Routing
- [x] Assets
- [x] Links
- [x] Markup Escape
- [x] Numbers
- [x] Custom Helpers
### Mailers
- [x] Overview
- [x] Basic Usage
- [x] Templates
- [x] Delivery
- [x] Share Code
- [x] Testing
### Assets
- [x] Overview
- [x] Preprocessors
- [x] Compressors
- [x] Content Delivery Network (CDN)
- [x] Use Your Own Assets Management Tool
### Command Line
- [x] Applications
- [x] Generators
- [x] Destroy
- [x] Database
- [x] Assets
- [x] Routes
- [x] Version

- [x] Все перечитать, проверить на ошибки и привести к единообразию

### CODE REVIEW

**Review by gbezyuk — COMMENTED** [review]
👍

**Comment by GeorgeGorbanev** [comment]
@gbezyuk тут все готово, можно мержить.

В отдельном ПР нужно переделать getting-started, он совсем плох. Потом добавить 2-3 раздела, которые добавились после моего форка и готово.

Можем призвать еще участников? Тут работы на полчаса-час осталось.

**Comment by sovetnik** [comment]
Релиз 1.0 версии в четверг [twitter](https://mobile.twitter.com/hanamirb/status/849305638119370756)

**Comment by gbezyuk** [comment]
@GeorgeGorbanev sorry for delay

**Review by gbezyuk — APPROVED** [review]

**Pull request merged**
